import type { FounderObject, ObjectRelationship } from './objectTypes'
import { nowISO } from './objectUtils'

const NOW = nowISO()

function rel(id: string, from: string, to: string, type: ObjectRelationship['type']): ObjectRelationship {
  return { id, fromObjectId: from, toObjectId: to, type, createdAt: NOW }
}

/** Stable seed IDs for relationships and cross-references. */
export const SEED_IDS = {
  founderOS: 'seed-project-founder-os',
  ascendOS: 'seed-project-ascend-os',
  modelProtocol: 'seed-project-model-protocol',
  year12: 'seed-project-year-12',
  goalAiOs: 'seed-goal-ai-os',
  goalPhysique: 'seed-goal-model-physique',
  taskWorkout: 'seed-task-workout',
  taskRead: 'seed-task-read-20',
  taskFounderOS: 'seed-task-move-founder-os',
  habitProtein: 'seed-habit-protein',
  habitReading: 'seed-habit-reading',
  decisionObjectFirst: 'seed-decision-object-first',
  ideaCategoryModes: 'seed-idea-category-modes',
} as const

export function createSeedObjects(): FounderObject[] {
  const objects: FounderObject[] = [
    {
      id: SEED_IDS.founderOS,
      type: 'project',
      title: 'FounderOS',
      summary: 'Build the AI operating system for life, goals, projects and daily execution.',
      area: 'systems',
      status: 'active',
      priority: 'high',
      tags: ['core', 'product'],
      source: 'seed',
      metadata: { nextAction: 'Ship Object Engine' },
      relationships: [
        rel('rel-1', SEED_IDS.founderOS, SEED_IDS.goalAiOs, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.ascendOS,
      type: 'project',
      title: 'AscendOS',
      summary: 'Personal AI command centre and life operating system vision.',
      area: 'systems',
      status: 'active',
      priority: 'high',
      tags: ['core', 'vision'],
      source: 'seed',
      metadata: {},
      relationships: [
        rel('rel-2', SEED_IDS.ascendOS, SEED_IDS.founderOS, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.modelProtocol,
      type: 'project',
      title: 'Model Protocol',
      summary: 'Training, nutrition and recovery system for a lean 79kg physique.',
      area: 'health',
      status: 'active',
      priority: 'high',
      tags: ['health', 'fitness'],
      source: 'seed',
      metadata: {},
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.year12,
      type: 'project',
      title: 'Year 12',
      summary: 'Academic excellence with sustainable study habits.',
      area: 'knowledge',
      status: 'active',
      priority: 'medium',
      tags: ['school', 'study'],
      source: 'seed',
      metadata: {},
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.goalAiOs,
      type: 'goal',
      title: 'Build AI Operating System',
      summary: 'Create an object-first AI OS that helps manage life and work.',
      area: 'systems',
      status: 'active',
      priority: 'high',
      tags: ['north-star'],
      source: 'seed',
      metadata: {},
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.goalPhysique,
      type: 'goal',
      title: 'Build Model Physique',
      summary: 'Reach and maintain a lean, strong 79kg physique.',
      area: 'health',
      status: 'active',
      priority: 'high',
      tags: ['health', 'fitness'],
      source: 'seed',
      metadata: {},
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.taskWorkout,
      type: 'task',
      title: 'Complete workout',
      area: 'health',
      status: 'active',
      priority: 'high',
      tags: ['daily'],
      source: 'seed',
      metadata: { projectId: SEED_IDS.modelProtocol },
      relationships: [
        rel('rel-3', SEED_IDS.taskWorkout, SEED_IDS.goalPhysique, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.taskRead,
      type: 'task',
      title: 'Read 20 pages',
      area: 'knowledge',
      status: 'active',
      priority: 'medium',
      tags: ['daily', 'reading'],
      source: 'seed',
      metadata: { projectId: SEED_IDS.year12 },
      relationships: [
        rel('rel-4', SEED_IDS.taskRead, SEED_IDS.year12, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.taskFounderOS,
      type: 'task',
      title: 'Move FounderOS forward',
      area: 'systems',
      status: 'active',
      priority: 'high',
      tags: ['daily'],
      source: 'seed',
      metadata: { projectId: SEED_IDS.founderOS },
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.habitProtein,
      type: 'habit',
      title: 'Daily protein',
      summary: 'Hit daily protein target consistently.',
      area: 'health',
      status: 'active',
      priority: 'medium',
      tags: ['nutrition', 'habit'],
      source: 'seed',
      metadata: {},
      relationships: [
        rel('rel-5', SEED_IDS.habitProtein, SEED_IDS.goalPhysique, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.habitReading,
      type: 'habit',
      title: 'Reading',
      summary: 'Daily reading habit for knowledge and growth.',
      area: 'knowledge',
      status: 'active',
      priority: 'medium',
      tags: ['habit', 'books'],
      source: 'seed',
      metadata: {},
      relationships: [],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.decisionObjectFirst,
      type: 'decision',
      title: 'FounderOS will be object-first',
      summary: 'All meaningful entities become FounderObjects with relationships.',
      area: 'systems',
      status: 'active',
      tags: ['architecture', 'decision'],
      source: 'seed',
      metadata: {},
      relationships: [
        rel('rel-6', SEED_IDS.decisionObjectFirst, SEED_IDS.founderOS, 'supports'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_IDS.ideaCategoryModes,
      type: 'idea',
      title: 'Category-specialised AI modes for Gym, Work, School etc.',
      summary: 'Context-aware AI modes tuned to life areas and object types.',
      area: 'systems',
      status: 'inbox',
      tags: ['ai', 'product'],
      source: 'seed',
      metadata: {},
      relationships: [
        rel('rel-7', SEED_IDS.ideaCategoryModes, SEED_IDS.founderOS, 'related_to'),
      ],
      createdAt: NOW,
      updatedAt: NOW,
    },
  ]

  return objects
}
