import type { Exercise } from './gymTypes'

export const GYM_EXERCISE_LIBRARY: Exercise[] = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'horizontal_push',
    compound: true,
    repRange: '6-10',
    restSeconds: 180,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    movementPattern: 'horizontal_push',
    compound: true,
    repRange: '8-12',
    restSeconds: 120,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'horizontal_pull',
    compound: true,
    repRange: '6-10',
    restSeconds: 150,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'vertical_pull',
    compound: true,
    repRange: '8-12',
    restSeconds: 90,
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'vertical_pull',
    compound: true,
    repRange: '5-10',
    restSeconds: 120,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'vertical_push',
    compound: true,
    repRange: '5-8',
    restSeconds: 180,
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    primaryMuscle: 'side_delts',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'isolation',
    compound: false,
    repRange: '12-20',
    restSeconds: 60,
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    primaryMuscle: 'rear_delts',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'horizontal_pull',
    compound: false,
    repRange: '12-20',
    restSeconds: 60,
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    movementPattern: 'isolation',
    compound: false,
    repRange: '10-15',
    restSeconds: 60,
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    difficulty: 'beginner',
    movementPattern: 'isolation',
    compound: false,
    repRange: '8-12',
    restSeconds: 75,
  },
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'squat',
    compound: true,
    repRange: '5-8',
    restSeconds: 210,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'hinge',
    compound: true,
    repRange: '6-10',
    restSeconds: 150,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'squat',
    compound: true,
    repRange: '10-15',
    restSeconds: 120,
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    movementPattern: 'hinge',
    compound: true,
    repRange: '8-12',
    restSeconds: 120,
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'isolation',
    compound: false,
    repRange: '12-20',
    restSeconds: 60,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'abs',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'isolation',
    compound: false,
    repRange: '8-15',
    restSeconds: 60,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    movementPattern: 'isolation',
    compound: false,
    repRange: '12-15',
    restSeconds: 75,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    movementPattern: 'vertical_push',
    compound: true,
    repRange: '8-12',
    restSeconds: 120,
  },
]

export function getExerciseById(id: string): Exercise | undefined {
  return GYM_EXERCISE_LIBRARY.find(e => e.id === id)
}

export function getExercisesForMuscle(muscle: string): Exercise[] {
  return GYM_EXERCISE_LIBRARY.filter(e =>
    e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle as Exercise['primaryMuscle']),
  )
}

export function findExerciseByName(name: string): Exercise | undefined {
  const lower = name.toLowerCase()
  return GYM_EXERCISE_LIBRARY.find(e => lower.includes(e.name.toLowerCase()) || e.name.toLowerCase().includes(lower))
}
