/**
 * Approved research seed data — isolated from application logic.
 * Update this file when new sources are administrator-approved.
 * Do not store copyrighted full text; metadata and paraphrased claims only.
 */
import type { GymEvidenceClaim, GymResearchSource } from './gymEvidenceTypes'

export const GYM_EVIDENCE_SEED_SOURCES: GymResearchSource[] = [
  {
    id: 'src-acsm-progression-2009',
    title: 'ACSM Position Stand: Progression Models in Resistance Training for Healthy Adults',
    authorsOrOrganisation: 'American College of Sports Medicine',
    year: 2009,
    publicationType: 'position_stand',
    doi: '10.1249/MSS.0b013e3181915670',
    url: 'https://journals.lww.com/acsm-msse/fulltext/2009/03000/progression_models_in_resistance_training_for.26.aspx',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['general_adults', 'beginners', 'intermediate_lifters'],
    outcomes: ['muscular strength', 'hypertrophy', 'muscular endurance', 'health'],
    limitations: ['Healthy adults focus; individual variation in response is expected.'],
    evidenceQuality: 'expert_consensus',
    summary: 'ACSM recommends progressive resistance training with periodised volume and intensity, using multiple sets and appropriate repetition ranges for specific goals.',
  },
  {
    id: 'src-who-pa-2020',
    title: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
    authorsOrOrganisation: 'World Health Organization',
    year: 2020,
    publicationType: 'guideline',
    url: 'https://www.who.int/publications/i/item/9789240015128',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['general_adults', 'older_adults'],
    outcomes: ['mortality risk', 'cardiometabolic health', 'muscular fitness', 'functional capacity'],
    limitations: ['Population-level guidance; not sport-specific periodisation detail.'],
    evidenceQuality: 'guideline',
    summary: 'WHO recommends adults perform muscle-strengthening activities involving major muscle groups on two or more days per week, alongside aerobic activity.',
  },
  {
    id: 'src-au-pa-adults',
    title: 'Australia\'s Physical Activity and Sedentary Behaviour Guidelines — Adults (18–64)',
    authorsOrOrganisation: 'Australian Government Department of Health',
    year: 2021,
    publicationType: 'guideline',
    url: 'https://www.health.gov.au/topics/physical-activity-and-exercise/physical-activity-and-exercise-guidelines-for-all-australians',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['general_adults'],
    outcomes: ['health', 'muscular fitness', 'adherence'],
    limitations: ['Broad public-health framing rather than advanced hypertrophy programming.'],
    evidenceQuality: 'guideline',
    summary: 'Australian guidelines recommend muscle-strengthening activities on at least two days each week, working major muscle groups, alongside regular aerobic activity.',
  },
  {
    id: 'src-schoenfeld-volume-2017',
    title: 'Dose-response relationship between weekly resistance training volume and increases in muscle mass',
    authorsOrOrganisation: 'Schoenfeld BJ, Ogborn D, Krieger JW',
    year: 2017,
    publicationType: 'meta_analysis',
    doi: '10.1080/02640414.2016.1210197',
    url: 'https://doi.org/10.1080/02640414.2016.1210197',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['intermediate_lifters', 'advanced_lifters'],
    outcomes: ['hypertrophy', 'weekly set volume'],
    limitations: ['Trained populations in included studies; recovery capacity varies individually.'],
    evidenceQuality: 'meta_analysis',
    summary: 'Meta-analytic evidence supports a dose-response relationship between weekly resistance-training set volume and muscle hypertrophy, with higher volumes within recoverable limits generally associated with greater gains.',
  },
  {
    id: 'src-schoenfeld-frequency-2016',
    title: 'Effects of Resistance Training Frequency on Measures of Muscle Hypertrophy: A Systematic Review and Meta-Analysis',
    authorsOrOrganisation: 'Schoenfeld BJ, Ogborn D, Krieger JW',
    year: 2016,
    publicationType: 'meta_analysis',
    doi: '10.1007/s40279-016-0543-8',
    url: 'https://doi.org/10.1007/s40279-016-0543-8',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['intermediate_lifters', 'general_adults'],
    outcomes: ['hypertrophy', 'training frequency'],
    limitations: ['Volume equated across frequencies in many comparisons; practical scheduling matters.'],
    evidenceQuality: 'meta_analysis',
    summary: 'When weekly volume is similar, training each muscle group at least twice per week tends to support hypertrophy outcomes better than once weekly in many analysed comparisons.',
  },
  {
    id: 'src-grgic-failure-2022',
    title: 'Effects of resistance training performed to repetition failure or non-failure on muscular strength and hypertrophy',
    authorsOrOrganisation: 'Grgic J, Schoenfeld BJ, Davies TB, et al.',
    year: 2022,
    publicationType: 'meta_analysis',
    doi: '10.1016/j.jshs.2021.07.007',
    url: 'https://doi.org/10.1016/j.jshs.2021.07.007',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'approved',
    population: ['intermediate_lifters', 'general_adults'],
    outcomes: ['hypertrophy', 'strength', 'proximity to failure'],
    limitations: ['Training to failure may increase fatigue; not always required for hypertrophy.'],
    evidenceQuality: 'meta_analysis',
    summary: 'Meta-analytic evidence indicates training close to momentary failure can support hypertrophy and strength, but stopping short of failure with adequate effort (e.g. RIR 1–3) can also be effective while reducing fatigue.',
  },
  {
    id: 'src-provisional-velocity-2020',
    title: 'Velocity-based training for strength and power (provisional summary)',
    authorsOrOrganisation: 'Sports science review consortium (provisional)',
    year: 2020,
    publicationType: 'systematic_review',
    reviewedAt: '2025-01-15T00:00:00.000Z',
    status: 'provisional',
    population: ['advanced_lifters'],
    outcomes: ['strength', 'power'],
    limitations: ['Provisional placeholder for emerging velocity-based methods; not used to override approved prescriptions.'],
    evidenceQuality: 'systematic_review',
    summary: 'Emerging evidence suggests velocity monitoring may help autoregulate load; requires individual calibration and is not yet part of default prescriptions.',
  },
]

export const GYM_EVIDENCE_SEED_CLAIMS: GymEvidenceClaim[] = [
  {
    id: 'claim-acsm-hypertrophy-reps',
    sourceId: 'src-acsm-progression-2009',
    variable: 'rep_range',
    goals: ['muscle_growth', 'general_fitness'],
    populations: ['general_adults', 'beginners', 'intermediate_lifters'],
    muscles: ['chest', 'back', 'quads'],
    claim: 'For hypertrophy-oriented training, moderate repetition ranges (approximately 8–12) are a commonly recommended starting point in ACSM progression guidance.',
    valueRange: { min: 8, max: 12, unit: 'reps' },
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['hypertrophy', 'reps'],
  },
  {
    id: 'claim-acsm-strength-reps',
    sourceId: 'src-acsm-progression-2009',
    variable: 'rep_range',
    goals: ['strength', 'powerlifting'],
    populations: ['intermediate_lifters', 'advanced_lifters'],
    claim: 'For maximal strength development, lower repetition ranges with heavier loads are commonly prescribed in progression models.',
    valueRange: { min: 1, max: 6, unit: 'reps' },
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['strength', 'reps'],
  },
  {
    id: 'claim-acsm-sets-beginner',
    sourceId: 'src-acsm-progression-2009',
    variable: 'sets_per_exercise',
    goals: ['general_fitness', 'muscle_growth', 'strength'],
    populations: ['beginners'],
    claim: 'Beginners often start with fewer sets per exercise and progress gradually as technique and tolerance improve.',
    valueRange: { min: 1, max: 3, unit: 'sets' },
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['beginner', 'sets'],
  },
  {
    id: 'claim-acsm-sets-intermediate',
    sourceId: 'src-acsm-progression-2009',
    variable: 'sets_per_exercise',
    goals: ['muscle_growth', 'strength', 'general_fitness'],
    populations: ['intermediate_lifters', 'advanced_lifters'],
    claim: 'Multiple sets per exercise are typically used for intermediate and advanced trainees pursuing strength or hypertrophy.',
    valueRange: { min: 2, max: 4, unit: 'sets' },
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['sets'],
  },
  {
    id: 'claim-acsm-rest-compound',
    sourceId: 'src-acsm-progression-2009',
    variable: 'rest_interval',
    goals: ['strength', 'powerlifting', 'muscle_growth'],
    populations: ['general_adults', 'intermediate_lifters'],
    claim: 'Longer rest intervals (roughly 2–3 minutes) are commonly recommended between heavy compound sets to maintain performance.',
    valueRange: { min: 120, max: 180, unit: 'seconds' },
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['rest', 'compound'],
  },
  {
    id: 'claim-acsm-progression',
    sourceId: 'src-acsm-progression-2009',
    variable: 'progression',
    goals: ['muscle_growth', 'strength', 'general_fitness'],
    populations: ['general_adults', 'beginners', 'intermediate_lifters'],
    claim: 'Progressive overload through gradual increases in load, repetitions, or sets over time is a core principle of resistance-training progression.',
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['progression'],
  },
  {
    id: 'claim-acsm-deload',
    sourceId: 'src-acsm-progression-2009',
    variable: 'deloading',
    goals: ['muscle_growth', 'strength', 'general_fitness'],
    populations: ['general_adults', 'intermediate_lifters', 'advanced_lifters'],
    claim: 'Planned reductions in training volume or intensity (deloads) can help manage fatigue and support long-term progression.',
    evidenceLevel: 'expert_consensus',
    status: 'approved',
    tags: ['deload'],
  },
  {
    id: 'claim-who-frequency',
    sourceId: 'src-who-pa-2020',
    variable: 'frequency',
    goals: ['general_fitness', 'health_maintenance', 'weight_loss'],
    populations: ['general_adults'],
    claim: 'Major muscle groups should be trained with muscle-strengthening activities on at least two days per week for broad health benefits.',
    valueRange: { min: 2, max: 7, unit: 'days_per_week' },
    evidenceLevel: 'guideline',
    status: 'approved',
    tags: ['frequency', 'health'],
  },
  {
    id: 'claim-au-frequency',
    sourceId: 'src-au-pa-adults',
    variable: 'frequency',
    goals: ['general_fitness', 'health_maintenance'],
    populations: ['general_adults'],
    claim: 'Australian guidelines recommend strengthening activities involving major muscle groups on at least two days each week.',
    valueRange: { min: 2, max: 7, unit: 'days_per_week' },
    evidenceLevel: 'guideline',
    status: 'approved',
    tags: ['frequency', 'health'],
  },
  {
    id: 'claim-schoenfeld-weekly-volume',
    sourceId: 'src-schoenfeld-volume-2017',
    variable: 'weekly_sets_per_muscle',
    goals: ['muscle_growth'],
    populations: ['intermediate_lifters', 'advanced_lifters'],
    claim: 'Higher weekly set volumes per muscle group are generally associated with greater hypertrophy up to individual recovery limits.',
    valueRange: { min: 10, max: 20, unit: 'sets_per_week' },
    evidenceLevel: 'meta_analysis',
    status: 'approved',
    tags: ['volume', 'hypertrophy'],
  },
  {
    id: 'claim-schoenfeld-frequency-2x',
    sourceId: 'src-schoenfeld-frequency-2016',
    variable: 'frequency',
    goals: ['muscle_growth'],
    populations: ['intermediate_lifters'],
    claim: 'Training each muscle group about twice per week is a practical starting frequency for hypertrophy when weekly volume is distributed.',
    valueRange: { min: 2, max: 3, unit: 'sessions_per_week_per_muscle' },
    evidenceLevel: 'meta_analysis',
    status: 'approved',
    tags: ['frequency', 'hypertrophy'],
  },
  {
    id: 'claim-grgic-rpe-effort',
    sourceId: 'src-grgic-failure-2022',
    variable: 'proximity_to_failure',
    goals: ['muscle_growth', 'strength', 'general_fitness'],
    populations: ['intermediate_lifters', 'general_adults'],
    claim: 'Sets performed with high effort (near failure or 0–3 reps in reserve) can support hypertrophy; training slightly short of failure may reduce fatigue while remaining effective.',
    valueRange: { min: 0, max: 3, unit: 'rir' },
    evidenceLevel: 'meta_analysis',
    status: 'approved',
    tags: ['rpe', 'rir', 'effort'],
  },
  {
    id: 'claim-grgic-rpe-beginner',
    sourceId: 'src-grgic-failure-2022',
    variable: 'rpe',
    goals: ['general_fitness', 'muscle_growth'],
    populations: ['beginners'],
    claim: 'Beginners may benefit from conservative effort targets while learning technique, progressing effort gradually rather than always training to failure.',
    valueRange: { min: 6, max: 8, unit: 'rpe' },
    evidenceLevel: 'meta_analysis',
    status: 'approved',
    tags: ['beginner', 'rpe'],
  },
  {
    id: 'claim-weight-loss-quality',
    sourceId: 'src-who-pa-2020',
    variable: 'exercise_order',
    goals: ['weight_loss', 'general_fitness'],
    populations: ['general_adults'],
    claim: 'Resistance training quality and consistency support lean mass retention during weight management; high-repetition circuits are not required for this purpose.',
    evidenceLevel: 'guideline',
    status: 'approved',
    tags: ['weight_loss', 'quality'],
  },
]
