/** Retention limits for persisted cognitive storage. */
export const COGNITIVE_RETENTION = {
  MAX_EVIDENCE_PER_BELIEF: 30,
  MAX_HISTORY_PER_BELIEF: 20,
  MAX_TIMELINE: 150,
  MAX_HYPOTHESES: 12,
  MAX_UNKNOWNS: 20,
  MAX_OPEN_QUESTIONS: 10,
  MAX_CONTRADICTIONS: 30,
  MAX_BELIEFS: 100,
  MAX_EVIDENCE_SUMMARY_CHARS: 120,
  MAX_STATEMENT_CHARS: 280,
  STORAGE_BUDGET_BYTES: 2.5 * 1024 * 1024,
  STORAGE_HARD_LIMIT_BYTES: 3 * 1024 * 1024,
} as const
