import type { KnowledgeRecord } from './knowledgeTypes'
import { newKnowledgeId, nowISO } from './knowledgeUtils'

const NOW = nowISO()

export const SEED_KNOWLEDGE_IDS = {
  buildSoftware: 'seed-know-build-software',
  objectFirst: 'seed-know-object-first',
  memoryNotKnowledge: 'seed-know-memory-not-knowledge',
  dailyFocus: 'seed-know-daily-focus',
  healthProtects: 'seed-know-health-protects',
  examTraining: 'seed-know-exam-training',
  domainsNoData: 'seed-know-domains-no-data',
} as const

export function createSeedKnowledge(): KnowledgeRecord[] {
  return [
    {
      id: SEED_KNOWLEDGE_IDS.buildSoftware,
      type: 'principle',
      title: 'Build software, not endless plans',
      principle: 'Ship working software over perfect roadmaps.',
      explanation: 'Planning has diminishing returns. Every sprint should produce something runnable.',
      domain: 'founder',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['execution', 'product'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.objectFirst,
      type: 'framework',
      title: 'Object-first architecture',
      principle: 'Model reality as structured FounderObjects before building features on top.',
      explanation: 'Objects are the foundation for memory, knowledge, reasoning, and executive layers.',
      domain: 'systems',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['architecture', 'founderos'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.memoryNotKnowledge,
      type: 'principle',
      title: 'Memory is not knowledge',
      principle: 'Memories record what happened; knowledge captures what should guide the future.',
      explanation: 'A decision memory is an event. The principle extracted from it is knowledge.',
      domain: 'systems',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['memory', 'knowledge'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.dailyFocus,
      type: 'rule',
      title: 'Daily Executive Focus',
      principle: 'One primary focus per day, supported by the Executive Engine.',
      explanation: 'Avoid diffused effort. Let attention scoring pick the single highest-leverage action.',
      domain: 'founder',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['executive', 'focus'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.healthProtects,
      type: 'principle',
      title: 'Health protects output',
      principle: 'Sleep, nutrition, and movement are prerequisites for sustained high performance.',
      explanation: 'Skipping recovery to work harder is a false economy. Health signals inform executive decisions.',
      domain: 'health',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['health', 'recovery'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.examTraining,
      type: 'rule',
      title: 'Exam period training',
      principle: 'During exam periods, reduce training volume and protect study blocks.',
      explanation: 'Maintain habits at maintenance level. Do not chase PRs when cognitive load is high.',
      domain: 'gym',
      confidence: 'medium',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['school', 'training', 'periodisation'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: SEED_KNOWLEDGE_IDS.domainsNoData,
      type: 'framework',
      title: 'Domains do not own data',
      principle: 'Domain intelligence reads from shared engines; it does not silo objects or memories.',
      explanation: 'Gym, school, and founder domains are lenses over the same Object/Memory/Knowledge layers.',
      domain: 'systems',
      confidence: 'high',
      source: 'seed',
      relatedObjectIds: [],
      relatedMemoryIds: [],
      tags: ['architecture', 'domains'],
      usageCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ]
}
