import type { DomainDefinition, DomainId } from './domainTypes'

export const DOMAIN_REGISTRY: Record<DomainId, DomainDefinition> = {
  founder: {
    id: 'founder',
    name: 'Founder',
    description: 'Build valuable software without destroying school or health.',
    keywords: ['founderos', 'ascendos', 'app', 'product', 'cursor', 'coding', 'startup', 'business', 'software', 'build'],
    objectAreas: ['systems'],
    signalTypes: ['coding_session', 'task', 'idea'],
    knowledgeDomains: ['founder'],
    priorityWeight: 1.0,
  },
  school: {
    id: 'school',
    name: 'School',
    description: 'Protect academic performance and future optionality.',
    keywords: ['school', 'study', 'economics', 'exam', 'assignment', 'year 12', 'atar', 'university', 'class'],
    objectAreas: ['knowledge'],
    signalTypes: ['event', 'reminder', 'task', 'document'],
    knowledgeDomains: ['school'],
    priorityWeight: 1.1,
  },
  health: {
    id: 'health',
    name: 'Health',
    description: 'Maintain physical and mental performance.',
    keywords: ['gym', 'workout', 'sleep', 'recovery', 'nutrition', 'body', 'energy', 'mood', 'protein', 'water'],
    objectAreas: ['health'],
    signalTypes: ['health', 'workout'],
    knowledgeDomains: ['health', 'gym'],
    priorityWeight: 1.05,
  },
  finance: {
    id: 'finance',
    name: 'Finance',
    description: 'Improve financial capability and reduce avoidable risk.',
    keywords: ['money', 'finance', 'income', 'savings', 'investing', 'business', 'work', 'career', 'runway'],
    objectAreas: ['career'],
    signalTypes: ['message', 'task', 'reminder'],
    knowledgeDomains: ['finance', 'work'],
    priorityWeight: 0.85,
  },
  relationships: {
    id: 'relationships',
    name: 'Relationships',
    description: 'Protect important relationships and communication.',
    keywords: ['family', 'friends', 'relationship', 'social', 'communication', 'parent', 'friend'],
    objectAreas: [],
    signalTypes: ['message', 'event'],
    knowledgeDomains: ['life'],
    priorityWeight: 0.8,
  },
  personal_growth: {
    id: 'personal_growth',
    name: 'Personal Growth',
    description: 'Compound skill, maturity, and self-awareness.',
    keywords: ['reading', 'learning', 'character', 'discipline', 'journal', 'reflection', 'habits', 'lesson'],
    objectAreas: ['growth'],
    signalTypes: ['idea', 'document'],
    knowledgeDomains: ['life'],
    priorityWeight: 0.75,
  },
  systems: {
    id: 'systems',
    name: 'Systems',
    description: 'Keep the operating system clean and usable.',
    keywords: ['system', 'organisation', 'organization', 'planning', 'inbox', 'capture', 'review', 'routine', 'founderos'],
    objectAreas: ['systems'],
    signalTypes: ['system', 'activity'],
    knowledgeDomains: ['systems'],
    priorityWeight: 0.9,
  },
}

export const DOMAIN_IDS: DomainId[] = Object.keys(DOMAIN_REGISTRY) as DomainId[]
